-- ============================================================
-- Secure Document Vault
-- V001 : Core Database Baseline
--
-- 역할:
--   SDV의 Source / Permission / Policy / Vault /
--   Audit / Security / Event / Sync 기본 스키마 생성
--
-- 주의:
--   document_chunks + pgvector는 V002에서 생성한다.
-- ============================================================


-- ============================================================
-- 1. Source Connections
-- 외부/로컬 문서 Source 연결 정보
-- ============================================================
CREATE TABLE source_connections (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- GOOGLE_DRIVE, LOCAL_VAULT 등 Source 종류
                                    type VARCHAR(50) NOT NULL,

    -- 사용자에게 보여줄 Source 이름
                                    display_name VARCHAR(255) NOT NULL,

    -- ACTIVE, DISABLED, ERROR 등
                                    status VARCHAR(30) NOT NULL,

    -- FULL, INCREMENTAL 등 동기화 방식
                                    sync_mode VARCHAR(30) NOT NULL,

    -- 실제 OAuth Token을 저장하지 않는다.
    -- 안전하게 보관된 Token의 참조값만 저장
                                    token_ref VARCHAR(500),

                                    last_sync_at TIMESTAMPTZ
);


-- ============================================================
-- 2. Source Sync Cursor
-- Google Drive 등의 증분 동기화 위치 저장
-- Source 하나당 하나의 활성 Cursor
-- ============================================================
CREATE TABLE source_sync_cursors (
                                     source_id BIGINT PRIMARY KEY,

                                     cursor TEXT NOT NULL,

                                     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_sync_cursor_source
                                         FOREIGN KEY (source_id)
                                             REFERENCES source_connections(id)
                                             ON DELETE CASCADE
);


-- ============================================================
-- 3. Source Documents
-- Google Drive / Local Vault 등의 문서를
-- SDV 내부의 공통 형태로 관리
-- ============================================================
CREATE TABLE source_documents (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  source_id BIGINT NOT NULL,

    -- 원본 시스템에서 사용하는 Document ID
                                  source_document_id VARCHAR(500) NOT NULL,

                                  name VARCHAR(500) NOT NULL,

                                  mime_type VARCHAR(150),

    -- 원본 Source의 revision/version
                                  source_version VARCHAR(255),

                                  modified_at TIMESTAMPTZ,

    -- SYNCED, READY, STALE, DELETED, FAILED 등
                                  state VARCHAR(30) NOT NULL,

                                  CONSTRAINT fk_source_document_source
                                      FOREIGN KEY (source_id)
                                          REFERENCES source_connections(id)
                                          ON DELETE CASCADE,

    -- 한 Source 안에서 같은 원본 문서가 중복 등록되는 것을 방지
                                  CONSTRAINT uq_source_document
                                      UNIQUE (source_id, source_document_id)
);


-- ============================================================
-- 4. Source Permissions
-- 원본 Source의 ACL(Access Control List)을 정규화하여 저장
-- ============================================================
CREATE TABLE source_permissions (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                    document_id BIGINT NOT NULL,

    -- USER, GROUP, DOMAIN, ANYONE 등
                                    principal_type VARCHAR(30) NOT NULL,

    -- email, group id, domain 등
                                    principal_value VARCHAR(500) NOT NULL,

    -- READ 등
                                    permission VARCHAR(30) NOT NULL,

                                    synced_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                    CONSTRAINT fk_source_permission_document
                                        FOREIGN KEY (document_id)
                                            REFERENCES source_documents(id)
                                            ON DELETE CASCADE
);


CREATE INDEX idx_source_permissions_document_id
    ON source_permissions(document_id);


CREATE INDEX idx_source_permissions_principal
    ON source_permissions(principal_type, principal_value);


-- ============================================================
-- 5. Document Security Labels
-- SDV 자체 보안 등급
-- PUBLIC / INTERNAL / CONFIDENTIAL / SECRET
-- ============================================================
CREATE TABLE document_security_labels (
                                          document_id BIGINT PRIMARY KEY,

                                          security_level VARCHAR(30) NOT NULL,

    -- SOURCE_MAPPING / MANUAL
                                          origin VARCHAR(30) NOT NULL,

                                          source_label VARCHAR(255),

                                          CONSTRAINT fk_security_label_document
                                              FOREIGN KEY (document_id)
                                                  REFERENCES source_documents(id)
                                                  ON DELETE CASCADE,

                                          CONSTRAINT chk_security_level
                                              CHECK (
                                                  security_level IN (
                                                                     'PUBLIC',
                                                                     'INTERNAL',
                                                                     'CONFIDENTIAL',
                                                                     'SECRET'
                                                      )
                                                  ),

                                          CONSTRAINT chk_security_label_origin
                                              CHECK (
                                                  origin IN (
                                                             'SOURCE_MAPPING',
                                                             'MANUAL'
                                                      )
                                                  )
);


-- ============================================================
-- 6. Overlay Policies
-- Source 권한 위에 추가적으로 적용되는 SDV 정책
--
-- 핵심 보안 원칙:
-- Source에서 DENY된 권한을 SDV가 ALLOW로 확장하지 않는다.
-- ============================================================
CREATE TABLE overlay_policies (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- USER, GROUP, ROLE 등
                                  subject_type VARCHAR(30) NOT NULL,

                                  subject_value VARCHAR(500) NOT NULL,

                                  security_level VARCHAR(30),

                                  action VARCHAR(50) NOT NULL,

    -- 주로 DENY 정책을 표현
                                  effect VARCHAR(20) NOT NULL,

                                  CONSTRAINT chk_overlay_effect
                                      CHECK (effect IN ('ALLOW', 'DENY'))
);


CREATE INDEX idx_overlay_policy_subject
    ON overlay_policies(subject_type, subject_value);


-- ============================================================
-- 7. AI Usage Policies
-- 문서 보안 등급별 AI 전송 정책
-- ============================================================
CREATE TABLE ai_usage_policies (
                                   security_level VARCHAR(30) PRIMARY KEY,

    -- LOCAL_ONLY
    -- EXTERNAL_ALLOWED
    -- AI_DENIED
                                   mode VARCHAR(30) NOT NULL,

                                   external_provider_allowed BOOLEAN NOT NULL DEFAULT FALSE,

                                   CONSTRAINT chk_ai_security_level
                                       CHECK (
                                           security_level IN (
                                                              'PUBLIC',
                                                              'INTERNAL',
                                                              'CONFIDENTIAL',
                                                              'SECRET'
                                               )
                                           ),

                                   CONSTRAINT chk_ai_policy_mode
                                       CHECK (
                                           mode IN (
                                                    'LOCAL_ONLY',
                                                    'EXTERNAL_ALLOWED',
                                                    'AI_DENIED'
                                               )
                                           )
);


-- ============================================================
-- 8. Local Vault Collections
-- 복잡한 폴더 구조 대신 MVP에서는 1단계 Collection 사용
-- ============================================================
CREATE TABLE local_vault_collections (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                         name VARCHAR(255) NOT NULL,

    -- Keycloak subject 값을 사용
                                         owner_subject VARCHAR(255) NOT NULL,

                                         created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX idx_vault_collection_owner
    ON local_vault_collections(owner_subject);


-- ============================================================
-- 9. Local Vault Objects
-- 실제 암호화된 원본 파일의 메타데이터
--
-- 중요:
-- 원본 파일 자체를 DB에 저장하지 않는다.
-- storage_key를 통해 암호화 파일을 찾는다.
-- ============================================================
CREATE TABLE local_vault_objects (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                     source_document_id BIGINT NOT NULL UNIQUE,

    -- 실제 저장 파일명을 그대로 사용하지 않고 내부 Storage Key 사용
                                     storage_key VARCHAR(500) NOT NULL UNIQUE,

    -- 원본 무결성 검증
                                     sha256 CHAR(64) NOT NULL,

    -- 향후 암호화 Key Rotation을 위한 버전
                                     key_version VARCHAR(50) NOT NULL,

                                     size BIGINT NOT NULL,

                                     CONSTRAINT chk_vault_object_size
                                         CHECK (size >= 0),

    CONSTRAINT fk_vault_object_document
        FOREIGN KEY (source_document_id)
        REFERENCES source_documents(id)
        ON DELETE CASCADE
);


-- ============================================================
-- 10. Audit Logs
-- 사용자/시스템의 주요 보안 행위를 기록
--
-- 중요:
-- 문서 원문, Token, Secret을 metadata에 넣지 않는다.
-- ============================================================
CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            actor VARCHAR(255),

                            action VARCHAR(100) NOT NULL,

                            target_type VARCHAR(100),

                            target_id VARCHAR(255),

                            result VARCHAR(30) NOT NULL,

                            reason_code VARCHAR(100),

                            trace_id VARCHAR(100),

    -- 구조화된 부가정보
                            metadata JSONB,

                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX idx_audit_logs_trace_id
    ON audit_logs(trace_id);


CREATE INDEX idx_audit_logs_created_at
    ON audit_logs(created_at);


-- ============================================================
-- 11. Security Findings
-- Oversharing, stale ACL 등의 보안 위험 탐지 결과
-- ============================================================
CREATE TABLE security_findings (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   type VARCHAR(100) NOT NULL,

                                   severity VARCHAR(30) NOT NULL,

    -- OPEN / ACKNOWLEDGED / RESOLVED
                                   status VARCHAR(30) NOT NULL,

                                   source_id BIGINT,

                                   document_id BIGINT,

    -- 보안 탐지 근거.
    -- 문서 원문 자체는 저장하지 않는다.
                                   evidence JSONB,

                                   detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT fk_security_finding_source
                                       FOREIGN KEY (source_id)
                                           REFERENCES source_connections(id)
                                           ON DELETE SET NULL,

                                   CONSTRAINT fk_security_finding_document
                                       FOREIGN KEY (document_id)
                                           REFERENCES source_documents(id)
                                           ON DELETE SET NULL,

                                   CONSTRAINT chk_security_finding_status
                                       CHECK (
                                           status IN (
                                                      'OPEN',
                                                      'ACKNOWLEDGED',
                                                      'RESOLVED'
                                               )
                                           )
);


CREATE INDEX idx_security_findings_status
    ON security_findings(status);


-- ============================================================
-- 12. Outbox Events
-- DB Transaction과 Kafka Event 발행 사이의 유실 방지
--
-- DB 변경을 먼저 Commit하고,
-- 아직 Kafka로 보내지 않은 Event를 이 테이블에서 재처리한다.
-- ============================================================
CREATE TABLE outbox_events (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 이벤트 중복 처리를 방지하기 위한 고유 ID
                               event_id UUID NOT NULL UNIQUE,

                               event_type VARCHAR(100) NOT NULL,

    -- 원문 / Token / Secret 저장 금지
                               payload JSONB NOT NULL,

    -- PENDING / PUBLISHED / FAILED
                               status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

                               created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               published_at TIMESTAMPTZ,

                               CONSTRAINT chk_outbox_status
                                   CHECK (
                                       status IN (
                                                  'PENDING',
                                                  'PUBLISHED',
                                                  'FAILED'
                                           )
                                       )
);


CREATE INDEX idx_outbox_events_pending
    ON outbox_events(status, created_at);


-- ============================================================
-- 13. Sync Runs
-- Source 동기화 작업의 실행 이력
-- ============================================================
CREATE TABLE sync_runs (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           source_id BIGINT NOT NULL,

    -- FULL / INCREMENTAL / MANUAL 등
                           mode VARCHAR(30) NOT NULL,

                           started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           ended_at TIMESTAMPTZ,

                           total INTEGER NOT NULL DEFAULT 0,

                           success INTEGER NOT NULL DEFAULT 0,

                           failed INTEGER NOT NULL DEFAULT 0,

    -- RUNNING / COMPLETED / FAILED 등
                           status VARCHAR(30) NOT NULL,

                           CONSTRAINT fk_sync_run_source
                               FOREIGN KEY (source_id)
                                   REFERENCES source_connections(id)
                                   ON DELETE CASCADE,

                           CONSTRAINT chk_sync_run_counts
                               CHECK (
                                   total >= 0
                                       AND success >= 0
                                       AND failed >= 0
                                   )
);


CREATE INDEX idx_sync_runs_source_id
    ON sync_runs(source_id);


CREATE INDEX idx_sync_runs_started_at
    ON sync_runs(started_at);