-- ============================================================
-- Secure Document Vault
-- V002 : pgvector / Document Chunk
--
-- 역할:
--   RAG Retrieval을 위한 document_chunks 테이블과
--   pgvector 확장(HNSW + cosine) 생성
--
-- 참고 (User-approved design decision):
--   Embedding Model : bge-m3:567m
--   Embedding Dimension : 1024
--   Similarity Metric : cosine distance
--   ANN Index : HNSW
--
-- 주의:
--   V001__baseline.sql은 수정하지 않는다.
-- ============================================================


-- ============================================================
-- 1. pgvector Extension
-- ============================================================
CREATE EXTENSION IF NOT EXISTS vector;


-- ============================================================
-- 2. Document Chunks
-- Source Document를 Parsing/Chunking/Embedding한 결과
-- RAG Retrieval의 최소 단위
-- ============================================================
CREATE TABLE document_chunks (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 document_id BIGINT NOT NULL,

    -- 같은 document_id 내에서 Chunk의 순서
                                 chunk_index INTEGER NOT NULL,

    -- PDF 등 페이지가 있는 문서의 페이지 번호
                                 page INTEGER,

    -- 문서 내 섹션/제목 등 위치 정보
                                 section VARCHAR(255),

    -- Chunk 원문 텍스트
                                 content TEXT NOT NULL,

    -- bge-m3:567m, 1024차원 Embedding
                                 embedding vector(1024) NOT NULL,

    -- Chunk 생성 시점의 원본 Source 문서 version(재인덱싱 판단 근거)
                                 source_version VARCHAR(255),

                                 CONSTRAINT fk_document_chunk_document
                                     FOREIGN KEY (document_id)
                                         REFERENCES source_documents(id)
                                         ON DELETE CASCADE
);


-- 문서 단위 Chunk 조회/삭제(재인덱싱 시 기존 Chunk 제거 등)를 지원하는 B-tree 색인
CREATE INDEX idx_document_chunks_document_id
    ON document_chunks(document_id);


-- Cosine distance 기반 ANN 검색을 위한 HNSW 색인
CREATE INDEX idx_document_chunks_embedding_hnsw
    ON document_chunks
    USING hnsw (embedding vector_cosine_ops);
