-- ============================================================
-- Secure Document Vault
-- V006 : Zero-Original-Persistence Correction (M07A, v1.4 SDV_v3.2_CORE_SPEC.md §2A.3)
--
-- 역할:
--   v1.4 동결 아키텍처("원본/평문 비보관")에 위배되는 기존 평문 영속 구조를
--   제거하고, 평문을 포함하지 않는 Embedding Candidate Index
--   (document_embedding_index)를 새로 만든다.
--
-- 제거 대상(구조 + 데이터, 둘 다 함께 사라진다 - DROP TABLE):
--   - document_extracted_content (V005) : document당 "현재 발행된 결과"
--     하나에 완전한 추출 텍스트(normalized_text)를 영구 보관했다 -
--     v1.4 §2A.3("완전한 추출 텍스트", "normalized_text"를 명시적으로
--     금지)에 정면으로 위배된다.
--   - document_chunks (V002, Legacy) : content TEXT NOT NULL 컬럼이 평문
--     Chunk를 영구 보관했다 - 역시 v1.4 §2A.3 위반. 이 테이블은 V002에서
--     만들어진 뒤 지금까지 이 Backend의 어떤 Java Entity/Repository도
--     대응한 적이 없다(M06까지 실제로 쓰거나 읽는 코드가 전혀 없었다) -
--     제거해도 깨지는 기존 애플리케이션 코드가 없다.
--
-- 신규 생성:
--   - document_embedding_index : 평문을 포함하지 않는 Embedding Candidate
--     Index(v1.4 §2A.2) - Embedding Vector, 일반화된 Locator, Source
--     Version, Keyed Content HMAC, Parser Version, Embedding Model만
--     담는다. 원본 Byte/완전한 텍스트/평문 Chunk/근거 텍스트/질문/답변/
--     Prompt 컬럼을 두지 않는다.
--
-- 주의:
--   V001~V005는 수정하지 않는다(Immutable, 이미 적용됨).
--   이 Migration은 물리적 소거(Disk Page/WAL/Replica/Snapshot/Backup)를
--   증명하지 않는다 - 논리적 Schema/Data 제거만 수행한다. 물리적 폐기
--   절차는 docs/runbooks/V006_ZERO_ORIGINAL_PERSISTENCE.md를 참고한다.
--   이 Migration은 원본/평문의 백업 사본을 별도로 만들지 않는다(되돌릴
--   수 있게 만들지 않는다 - 그것이 이 교정의 목적이다).
-- ============================================================


-- ============================================================
-- 1. 레거시 평문 영속 구조 제거(구조 + 데이터가 함께 사라진다)
-- ============================================================
DROP TABLE IF EXISTS document_extracted_content;

DROP TABLE IF EXISTS document_chunks;


-- ============================================================
-- 2. document_embedding_index : 평문 없는 Embedding Candidate Index
-- ============================================================
CREATE TABLE document_embedding_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    document_id BIGINT NOT NULL,

    -- 같은 Generation(document_id + source_version + parser_version +
    -- embedding_model 조합) 안에서 Chunk의 순서.
    chunk_index INTEGER NOT NULL,

    -- v3.2 Citation Model 어휘(PAGE/SLIDE/SHEET_RANGE/LINE_RANGE/SECTION/
    -- DOCUMENT, com.sdv.rag.domain.LocatorType과 동일 - V003
    -- chk_document_chunk_locator_type과 같은 집합을 그대로 재사용한다).
    locator_type VARCHAR(30) NOT NULL,
    locator_value TEXT NOT NULL,

    -- bge-m3:567m, 1024차원 Embedding(V002 Canonical 결정 유지 - CLAUDE.md
    -- "Vector 결정" 참고). 원문을 복원할 수 없는 Embedding Vector일 뿐이다.
    embedding vector(1024) NOT NULL,

    -- 이 Embedding Generation을 만든 시점의 원본 Source 문서 version
    -- (재인덱싱/Generation 교체 판단 근거) - 평문이 아니다.
    source_version VARCHAR(255) NOT NULL,

    -- 원본 Content의 Keyed Digest/HMAC(가역적 Content 자체가 아니다) - 동일
    -- Content 재확인/재사용 판단용. 이 컬럼에서 원문을 복원할 수 없다.
    content_hmac VARCHAR(64) NOT NULL,

    parser_version VARCHAR(50) NOT NULL,

    embedding_model VARCHAR(100) NOT NULL,

    indexed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_document_embedding_document
        FOREIGN KEY (document_id)
            REFERENCES source_documents(id)
            ON DELETE CASCADE,

    CONSTRAINT chk_document_embedding_locator_type
        CHECK (
            locator_type IN (
                             'PAGE',
                             'SLIDE',
                             'SHEET_RANGE',
                             'LINE_RANGE',
                             'SECTION',
                             'DOCUMENT'
                )
            ),

    -- 같은 문서의 같은 Generation(Source Version + Parser Version +
    -- Embedding Model) 안에서 같은 Chunk 순번이 중복되지 않도록 막는다.
    -- 원자적 Generation 교체(기존 Generation 삭제 + 새 Generation 삽입)
    -- 자체는 Application Transaction 경계(DocumentEmbeddingJpaRepository
    -- .replaceGeneration)가 책임진다 - 이 제약은 그 안에서 중복 삽입만
    -- 막는 마지막 방어선이다.
    CONSTRAINT uq_document_embedding_generation_chunk
        UNIQUE (document_id, source_version, parser_version, embedding_model, chunk_index)
);


-- 문서 단위 조회/삭제(재인덱싱 시 기존 Generation 제거, Source Disconnect 시
-- 일괄 제거 등)를 지원하는 B-tree 색인.
CREATE INDEX idx_document_embedding_document_id
    ON document_embedding_index(document_id);


-- Cosine distance 기반 ANN 검색을 위한 HNSW 색인(V002/pgvector Canonical
-- 결정 유지).
CREATE INDEX idx_document_embedding_hnsw
    ON document_embedding_index
    USING hnsw (embedding vector_cosine_ops);
