-- ============================================================
-- Secure Document Vault
-- V010 : Personal Sources, Explicit File Sharing, Reconnect Identity
--
-- M10B (docs/spec/SDV_v3.2_CORE_SPEC.md §2A.13/§2A.14) - v1.5 B-model:
-- an ordinary USER owns a private connection; only an explicit,
-- file-level, named-recipient share enters common discovery. Share
-- intent is persisted independently of connection health so a
-- disconnect never silently erases it, and reconnect requires a
-- verified stable provider account identity.
--
-- V001~V009는 Immutable이다 - 이 Migration은 새 Column/Table만 추가한다.
-- ============================================================

-- ============================================================
-- 1. source_connections: 재연결 시 비교할 안정적인 Provider 계정 식별자
--
-- Google Drive `about.user.permissionId` - 이메일/표시 이름이 아니라 Google이
-- 반환하는 안정적 식별자다. 최초 연결 시 채워지고, 이후 재연결 시도는 이 값과
-- 다시 확인한 permissionId가 일치할 때만 성공한다(GoogleDriveOAuthService).
-- 이 Migration 이전에 이미 연결된 기존 행은 NULL로 남아있다 - 다음 성공적인
-- (재)인증이 그 시점의 계정을 최초값으로 채택한다(추측하지 않는다).
-- ============================================================
ALTER TABLE source_connections
    ADD COLUMN provider_account_id VARCHAR(255);

-- ============================================================
-- 2. document_shares: 파일 단위 공유 의도
--
-- 연결 상태(source_connections.status)와 독립적으로 보존된다 - Disconnect가
-- 이 행을 지우거나 바꾸지 않는다(SourceConnectionService.disconnect 참고).
-- 하나의 활성(미철회) 공유만 문서당 존재할 수 있다(uq_document_shares_active) -
-- PATCH가 그 하나의 행의 수신자/등급/행위를 갱신하고, DELETE(명시적 unshare)는
-- 이 행을 되살릴 수 없게 철회한다(revoked_at) - 그 뒤 다시 공유하려면 새 행을
-- 만든다(같은 문서에 대해 여러 개의 철회된 이력 행이 남을 수 있다 - 감사 목적).
-- ============================================================
CREATE TABLE document_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 이 공유를 게시한 인증된 SDV subject - 클라이언트가 지정할 수 없다
    -- (서버가 항상 인증된 사용자로 채우고, 그 사용자가 실제로 이 문서의
    -- Source Owner인지 애플리케이션이 저장 전에 검증한다).
    publisher_subject VARCHAR(255) NOT NULL,

    source_id BIGINT NOT NULL
        CONSTRAINT fk_document_share_source
            REFERENCES source_connections(id),

    document_id BIGINT NOT NULL
        CONSTRAINT fk_document_share_document
            REFERENCES source_documents(id),

    -- PUBLIC/INTERNAL/CONFIDENTIAL/SECRET - 4개 canonical 값만 허용한다(CORE_SPEC
    -- §2A.13). 이 값은 policy.domain.SecurityLevel과 정확히 일치해야 한다.
    classification VARCHAR(30) NOT NULL
        CONSTRAINT chk_document_share_classification
            CHECK (classification IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'SECRET')),

    -- 콤마로 구분된 허용 행위 집합(예: "VIEW" 또는 "VIEW,DOWNLOAD") -
    -- source.domain.ShareAction의 canonical 이름만 담는다. 이번 M10B Slice가 실제로
    -- 강제하는 행위는 VIEW(Metadata Discovery)뿐이다 - DOWNLOAD는 M10C(SDV 인가
    -- 다운로드)가 검증을 추가하기 전까지 저장은 되지만 아무 Endpoint도 이를 근거로
    -- Content Byte를 내보내지 않는다.
    allowed_actions VARCHAR(255) NOT NULL,

    -- ADMIN 전용 - 게시자는 이 값을 절대 스스로 해제할 수 없다(SharedFileAdminController만
    -- 이 Column을 쓴다). true면 이 공유가 아무리 유효해도 즉시 거부된다.
    admin_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    admin_block_reason VARCHAR(500),

    -- 낙관적 동시성 - PATCH가 클라이언트의 마지막으로 읽은 값과 비교한다
    -- (SourceSharingService.updateShare). 매 성공적인 소유자 변경마다 증가한다.
    generation BIGINT NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- NULL이면 활성 공유다. 명시적 unshare(DELETE)만 이 값을 채운다 - Disconnect는
    -- 절대 이 Column을 건드리지 않는다(연결 중단과 공유 철회는 별개 연산이다).
    revoked_at TIMESTAMPTZ
);

CREATE INDEX idx_document_shares_publisher ON document_shares(publisher_subject);
CREATE INDEX idx_document_shares_document ON document_shares(document_id);

-- 문서당 활성(미철회) 공유는 최대 하나 - 재공유는 새 행이 아니라 기존 활성 행을
-- PATCH하거나(설정 변경), 철회 후 새로 POST한다.
CREATE UNIQUE INDEX uq_document_shares_active_document
    ON document_shares(document_id)
    WHERE revoked_at IS NULL;

-- ============================================================
-- 3. document_share_recipients: 하나의 공유에 결합된 지정 SDV subject ID
--
-- 이메일/도메인/Group 확장이 아니다 - 정확한 OIDC subject 문자열만 저장한다
-- (CORE_SPEC §2A.13 "no email-based identity matching, wildcard audience, group
-- system"). 빈 수신자 목록은 절대 "전체 공개"를 뜻하지 않는다 - 공유 생성 자체가
-- 최소 1개의 수신자를 요구한다(SourceSharingService 검증).
-- ============================================================
CREATE TABLE document_share_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    share_id BIGINT NOT NULL
        CONSTRAINT fk_document_share_recipient_share
            REFERENCES document_shares(id),

    recipient_subject VARCHAR(255) NOT NULL,

    CONSTRAINT uq_document_share_recipient
        UNIQUE (share_id, recipient_subject)
);

-- Discovery의 "이 요청자에게 부여된 활성 공유를 모두 찾는다" 조회가 이 Index를 탄다.
CREATE INDEX idx_document_share_recipients_recipient ON document_share_recipients(recipient_subject);
