-- ============================================================
-- Secure Document Vault
-- V011 : Share Concurrency Fencing + Administrative Restriction Persistence
--
-- M10B 보안 교정(2026-09-15, 같은 날 두 번째 세션) - 세 확인된 결함 그룹 중
-- A(동시 공유 수정)와 B(관리자 차단 우회)를 위한 스키마 변경. C(OAuth 재연결/
-- 공유 접근 Fencing)는 새 Column 하나(source_connections.connection_epoch)만
-- 필요하다 - 별도 Table 없이 여기서 함께 추가한다.
--
-- V001~V010은 Immutable이다 - 이 Migration은 새 Column/Table만 추가한다.
-- ============================================================

-- ============================================================
-- 1. source_connections: 연결 인가 세대(Connection/Authorization Epoch)
--
-- Refresh Access Token 버전(source_oauth_tokens 내부, 이 Migration이 손대지
-- 않는다)과는 완전히 다른 개념이다 - 이 값은 오직 Disconnect가 발생할 때만
-- 증가한다("connection authorization epoch", 일상적인 Token Refresh로는 절대
-- 증가하지 않는다). Disconnect 이전에 시작된 OAuth 시도(State Store에서 이미
-- consume되어 Token 교환/Identity 확인을 기다리던 시도 포함)가 나중에 완료돼도,
-- 이 값이 시작 시점과 달라졌다면 그 시도는 안전하게 거부된다
-- (GoogleDriveOAuthService.commitCredential).
-- ============================================================
ALTER TABLE source_connections
    ADD COLUMN connection_epoch BIGINT NOT NULL DEFAULT 1;

-- ============================================================
-- 2. document_share_restrictions: 관리자 차단을 파일의 정규 신원(Source+Document)에
-- 영구 결합한다 - document_shares.id(공유 게시마다 새로 발급됨)가 아니다.
--
-- 이전 결함: ADMIN이 document_shares.admin_blocked=true로 차단해도, 게시자가
-- 그 공유를 unshare(철회)한 뒤 같은 파일을 새 공유(새 id, admin_blocked
-- 기본값 false)로 재게시하면 차단이 사라졌다. 이제 SourceSharingService.createShare가
-- 이 Table에서 활성 차단이 있는지 확인해, 있으면 새로 만드는 공유를 처음부터
-- admin_blocked=true로 태어나게 한다 - ADMIN의 명시적 해제(SharedFileAdminController)
-- 만이 이 Table의 blocked를 false로 되돌릴 수 있고, 그래야만 이후 새로 게시되는
-- 공유가 차단 없이 시작된다. 기존에 이미 철회된 공유의 revoked_at은 이 Table이
-- 절대 되돌리지 않는다 - 그 공유는 영원히 철회된 채로 남는다.
-- ============================================================
CREATE TABLE document_share_restrictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_id BIGINT NOT NULL
        CONSTRAINT fk_document_share_restriction_source
            REFERENCES source_connections(id),

    document_id BIGINT NOT NULL
        CONSTRAINT fk_document_share_restriction_document
            REFERENCES source_documents(id),

    blocked BOOLEAN NOT NULL DEFAULT TRUE,
    blocked_reason VARCHAR(500),
    blocked_by_subject VARCHAR(255) NOT NULL,
    blocked_at TIMESTAMPTZ NOT NULL,

    cleared_by_subject VARCHAR(255),
    cleared_at TIMESTAMPTZ,

    -- 문서 하나당 관리 대상 제약 행은 하나뿐이다(블록/해제를 계속 같은 행에서 토글한다) -
    -- document_shares처럼 철회 이력을 별도 행으로 쌓지 않는다(요구된 "smallest persistent
    -- representation").
    CONSTRAINT uq_document_share_restriction UNIQUE (source_id, document_id)
);

CREATE INDEX idx_document_share_restrictions_document ON document_share_restrictions(document_id);
