-- V013: authenticated SDV user projection, explicit clearance and share audience.
-- Existing shares remain named-only. No row receives an implicit clearance.

CREATE TABLE sdv_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer VARCHAR(500) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    login_id VARCHAR(100) NOT NULL,
    normalized_login_id VARCHAR(100) NOT NULL,
    display_name VARCHAR(200),
    max_classification VARCHAR(30),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    authorization_revision BIGINT NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sdv_user_identity UNIQUE (issuer, subject),
    CONSTRAINT chk_sdv_user_clearance CHECK (
        max_classification IS NULL OR
        max_classification IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'SECRET')
    ),
    CONSTRAINT chk_sdv_user_revision CHECK (authorization_revision > 0)
);

CREATE INDEX idx_sdv_users_login_lookup
    ON sdv_users(issuer, normalized_login_id, active);

ALTER TABLE document_shares
    ADD COLUMN audience VARCHAR(30);

UPDATE document_shares SET audience = 'NAMED_USERS' WHERE audience IS NULL;

ALTER TABLE document_shares
    ALTER COLUMN audience SET NOT NULL;

ALTER TABLE document_shares
    ADD CONSTRAINT chk_document_share_audience
        CHECK (audience IN ('ALL_AUTHENTICATED', 'NAMED_USERS'));

ALTER TABLE document_share_recipients
    ADD COLUMN recipient_user_id BIGINT;

ALTER TABLE document_share_recipients
    ADD CONSTRAINT fk_document_share_recipient_user
        FOREIGN KEY (recipient_user_id) REFERENCES sdv_users(id);

CREATE INDEX idx_document_share_recipients_user
    ON document_share_recipients(recipient_user_id);

