-- ============================================================
-- Secure Document Vault (SDV)
-- Flyway afterMigrate callback: grant runtime DML privileges to `sdv`.
--
-- Runs as the Flyway/migration identity (spring.flyway.user, currently
-- sdv_user - see application-local.yml / application-compose.yml for
-- why that is a local-development compromise, not a production one).
--
-- Loaded only in the `local` and `compose` Spring profiles
-- (spring.flyway.locations there adds classpath:db/callback). Tests use
-- the default classpath:db/migration only, so no test needs a role
-- named `sdv` to exist.
--
-- Fires after every `flyway migrate` call in those profiles: on a fresh
-- database (after V001/V002 create the schema), on every application
-- startup thereafter (schema already at the latest version - zero
-- pending migrations, callback still runs), and again after each future
-- V003+ migration. It is idempotent and safe to re-run.
--
-- Scope: every ordinary application table currently in schema `public`
-- (source_connections, source_sync_cursors, source_documents,
-- source_permissions, document_security_labels, overlay_policies,
-- ai_usage_policies, local_vault_collections, local_vault_objects,
-- audit_logs, security_findings, outbox_events, sync_runs from V001,
-- and document_chunks from V002) - discovered dynamically by relkind
-- ('r' = ordinary table), NOT a fixed list, so a future V003+ table is
-- covered automatically the next time this callback runs. The Flyway
-- ledger (flyway_schema_history) is explicitly excluded by name and is
-- never granted, not even transiently: the loop skips it outright
-- rather than granting to ALL TABLES and revoking afterwards.
--
-- Deliberately NOT done here (see docs/handoff for rationale):
--   * No ALTER DEFAULT PRIVILEGES - default privileges are scoped to the
--     role that defines them (or a role named via FOR ROLE): they apply
--     only to objects that role itself later creates, not to objects any
--     other role creates. Since Flyway/sdv_user is the only identity that
--     creates schema objects here, that particular scoping would not by
--     itself be a problem. The real risk is registration order on a fresh
--     database: if default privileges were registered as sdv_user before
--     Flyway creates the ledger table (also as sdv_user), the ledger would
--     inherit them too - exactly the runtime grant on flyway_schema_history
--     this policy must never have. An explicit, ledger-excluding grant
--     loop avoids that order-dependent risk entirely instead of relying on
--     when the default-privilege registration happens to run relative to
--     the ledger table's own creation.
--   * No sequence GRANTs of any kind - V001/V002 identity columns
--     (GENERATED BY DEFAULT AS IDENTITY) use internally owned sequences
--     (pg_depend deptype='i'); INSERT works without USAGE/SELECT on the
--     sequence. If a future table needs explicit nextval()/setval() by
--     `sdv`, that is a new, narrow, explicit grant - never ALL SEQUENCES.
--   * No ownership transfer, no schema CREATE grant to `sdv`.
--   * No PUBLIC CONNECT/TEMPORARY changes - left exactly as the cluster
--     default; that means `sdv` can also connect to the `postgres`
--     database and create temporary tables, same as any other role,
--     which this policy does not attempt to restrict.
-- ============================================================

DO $$
DECLARE
	t regclass;
BEGIN
	FOR t IN
		SELECT c.oid::regclass
		FROM pg_class c
		WHERE c.relnamespace = 'public'::regnamespace
		  AND c.relkind = 'r'
		  AND c.relname <> 'flyway_schema_history'
	LOOP
		EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %s TO sdv', t);
	END LOOP;
END
$$;

-- Defence in depth: even though the loop above never touches it,
-- explicitly ensure the migration ledger carries no runtime grant.
REVOKE ALL ON TABLE public.flyway_schema_history FROM sdv;
